### PR TITLE
setup-and-mobile-first Pull Request

### PR DESCRIPTION
**Pull request by gilberthappi**
Adding Headings
Adding Styling
Add Readme
Adding Main branch folders

### CODE REVIEW

**Review by souad988 — COMMENTED** [review]
Hi @gilberthappi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional readme file kindly use microverse readme template and customize with your own content , also the branch name is not descriptive please change it to something that refers better to the work done in this feature exp: mobile_headline ...

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by souad988 — COMMENTED** [review]
Hi @gilberthappi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional readme file kindly use microverse readme template and customize with your own content , also the branch name is not descriptive please change it to something that refers better to the work done in this feature exp: mobile_headline ...

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by zeff96 — COMMENTED** [review]
Hi @gilberthappi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional readme file kindly use the [microverse readme template](https://github.com/microverseinc/readme-template#readme) and customize it with your own content, also the branch name is not descriptive please change it to something that refers better to the work done in this feature exp: mobile_headline ...

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Cabraham1 — COMMENTED** [review]
# Required Changes :recycle:
almost-there

## Hey @gilberthappi   :wave:

## Highlights :1st_place_medal:

✔️ Following GitHubflow
✔️ Following some requirements

- [ ] Unfortunately, you have submitted a project that is not professional and does not includes all the headers/sections present in [readme template](https://github.com/microverseinc/readme-template)📖
- [ ] Note that the placeholders in README file that are meant to guide you on the contents of each of the sections. They are not meant to instruct users on how to contribute to the code so please ensure that you remove them.
- [ ] Please ensure that you professionally document the README file to reflect the project 😄
- [ ] Please make sure that you use descriptive names for your branche (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars) 
### _**Microverse README template**_ 🔽
image

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
